version: '3.9'

services:
  db:
    image: postgres:15
    container_name: note_db
    restart: always
    environment:
      POSTGRES_DB: note_db
      POSTGRES_USER: note_user
      POSTGRES_PASSWORD: note_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: