# Generated by Django 4.2.21 on 2025-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes_files/'),
        ),
    ]
