# Generated by Django 4.2.21 on 2025-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='capacity',
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
